SELECT 
    u.USER_ID, 
    u.NICKNAME, 
    CONCAT(CITY, " ", STREET_ADDRESS1, " " , STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 12)) AS '전화번호'
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY u.USER_ID DESC