SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 09 AND HOUR(DATETIME) <= 19 
AND MINUTE(DATETIME) >= 0 AND MINUTE(DATETIME) <= 59
GROUP BY HOUR(DATETIME)
ORDER BY HOUR