# YEAR_DEV: 연도별 가장 큰 대장균 크기 - 각 대장균 크기 (즉, 최대에서 뺀 값)
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY as YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC