SELECT
    i.ID,
    n.FISH_NAME,
    i.LENGTH
FROM FISH_INFO i 
JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) m
on m.FISH_TYPE = i.FISH_TYPE AND m.MAX_LEN = i.LENGTH
ORDER BY i.ID ASC;