SELECT
    s.SCORE,
    e.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) s
JOIN HR_EMPLOYEES e ON e.EMP_NO = s.EMP_NO
WHERE s.SCORE = (
    SELECT MAX(SUM_SCORE)
    FROM (
        SELECT SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) t
);