SELECT b.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES s JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
WHERE s.SALES_DATE >= '2022-01-01' AND s.SALES_DATE < '2022-02-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;