SELECT a.CATEGORY, b.MAX_PRICE, a.PRODUCT_NAME
FROM FOOD_PRODUCT a 
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ) b ON a.CATEGORY = b.CATEGORY
    AND a.PRICE = b.MAX_PRICE
ORDER BY MAX_PRICE DESC;